export let config = {
  AZURE_ORG: process.env.REACT_APP_PIPELINE_ORG
    ? process.env.REACT_APP_PIPELINE_ORG
    : "",
  AZURE_PIPELINE_ACCESS_TOKEN: process.env.REACT_APP_PIPELINE_ACCESS_TOKEN
    ? process.env.REACT_APP_PIPELINE_ACCESS_TOKEN
    : "",
  AZURE_PROJECT: process.env.REACT_APP_PIPELINE_PROJECT
    ? process.env.REACT_APP_PIPELINE_PROJECT
    : "",
  GITHUB_MANIFEST_USERNAME: "",
  MANIFEST: "",
  MANIFEST_ACCESS_TOKEN: "",
  STORAGE_ACCOUNT_KEY: process.env.REACT_APP_STORAGE_ACCESS_KEY
    ? process.env.REACT_APP_STORAGE_ACCESS_KEY
    : "",
  STORAGE_ACCOUNT_NAME: process.env.REACT_APP_STORAGE_ACCOUNT_NAME
    ? process.env.REACT_APP_STORAGE_ACCOUNT_NAME
    : "",
  STORAGE_PARTITION_KEY: process.env.REACT_APP_STORAGE_PARTITION_KEY
    ? process.env.REACT_APP_STORAGE_PARTITION_KEY
    : "",
  STORAGE_TABLE_NAME: process.env.REACT_APP_STORAGE_TABLE_NAME
    ? process.env.REACT_APP_STORAGE_TABLE_NAME
    : ""
};
